# Butterfly ä¸»é¢˜é…ç½®æ–‡ä»¶
# --------------------------------------
# ä¸»é¢˜é…ç½®
menu:
  ä¸»é¡µ: / || fas fa-home
  åšæ–‡ || fa fa-graduation-cap:
    åˆ†ç±»: /categories/ || fa fa-archive
    æ ‡ç­¾: /tags/ || fa fa-tags
    å½’æ¡£: /archives/ || fa fa-folder-open
  ç”Ÿæ´» || fas fa-list:
    åˆ†äº«: /share/ || fa fa-comments-o
    ç›¸å†Œ: /photos/ || fa fa-camera-retro
    éŸ³ä¹: /music/ || fa fa-music
    å½±è§†: /movies/ || fas fa-video
  å‹é“¾: /links/ || fa fa-link
  ç•™è¨€æ¿: /comment/ || fa fa-paper-plane
  #ç•™è¨€æ¿: /messageboard/ || fa fa-paper-plane
  å…³äºç¬”è€…: /about/ || fas fa-heart  


# Code Blocks (ä»£ç å—æ ·å¼)
# --------------------------------------
highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button æ˜¯å¦æ˜¾ç¤ºå¤åˆ¶æŒ‰é’®
highlight_lang: true # show the code language å±•ç¤ºä»£ç å—è¯­è¨€
highlight_shrink: false # true: æ‰“å¼€æ–‡ç« é»˜è®¤æŠ˜å ä»£ç å—å†…å®¹ / false: æ‰“å¼€æ–‡ç« é»˜è®¤å±•å¼€ä»£ç å—å†…å®¹
highlight_height_limit: false # unit: px
code_word_wrap: false #æ˜¯å¦å…³é—­æ»šåŠ¨æ¡

# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "åäº†ï¼æ²¡æ‰¾åˆ° ${query}" # å¦‚æœæ²¡æœ‰æŸ¥åˆ°å†…å®¹ç›¸å…³å†…å®¹æ˜¾ç¤º

# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (å¼€å¯æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # sourceèª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨æå¤©apiçš„éš¨æ©ŸèªéŒ„ï¼ˆç°¡é«”ï¼‰
  # source: 2  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰
  # source: 3  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰
  # source: 4  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœæœ‰è‹±æ–‡é€—å·' , ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &#44;
  # å¦‚æœæœ‰è‹±æ–‡åŒå¼•å·' " ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &quot;
  # å¼€å¤´ä¸å…è¨±è½¬ä¹‰å­—å…ƒï¼Œå¦‚éœ€è¦ï¼Œè¯·æŠŠæ•´å€‹å¥å­ç”¨åŒå¼•å·åŒ…ä½
  # å¦‚æœå…³é—­æ‰“å­—æ•ˆæœï¼Œsubtitleåªä¼šç°ç¤ºsubçš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - å¹¿å‘Šä½ğŸª§æ‹›ç§Ÿ
    - æ‹›ç§ŸğŸª§å¹¿å‘Šä½
#    - å¹¿å‘Šä½ğŸª§æ‹›ç§Ÿ

