# Butterfly ä¸»é¢˜é…ç½®æ–‡ä»¶
# https://butterfly.js.org/posts/dc584b87/
# --------------------------------------
# ä¸»é¢˜é…ç½®
title: è¥¿éƒŠæœ‰å¯†æ— ç¥å›å‡ºé‡å›´
description: 'ä¸€ä¸ªäºº'
keywords:
author: zip95297
language: zh-CN
timezone: Asia/Shanghai

url: http://zip95297.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

nav:
  # å°èˆªæ¬„ Logo åœ–ç‰‡
  logo: 
  # æ˜¯å¦é¡¯ç¤ºæ¨™é¡Œ
  display_title: true
  # æ˜¯å¦å›ºå®šå°èˆªæ¬„
  fixed: false

# é¦–é¡µæ–‡ç« å¸ƒå±€ 5 / 7
index_layout: 7
# åŠ è½½åŠ¨ç”»
preloader: true
# æ˜¯å¦é¡¯ç¤ºè¿”å›é ‚éƒ¨æŒ‰éˆ•
back2top: true
# é¦–é¡µå›¾ç‰‡
index_img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg2.webp
top_img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg2.webp
# èƒŒæ™¯å›¾
background: url(https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg2.webp)
# é¡µè„šå›¾
footer_img: true
# favicon æµè§ˆå™¨çš„å›¾æ ‡
favicon: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/profile.webp?raw=true
# å½’æ¡£é¡µ çš„å›¾ç‰‡
archive_img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg1.webp
# åˆ†ç±»é¡µ çš„å›¾ç‰‡
category_img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg4.webp
# tag çš„å›¾ç‰‡
tag_img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/bg3.webp
# ç¯ç®±æ•ˆæœ
lightbox: 

# è´ŠåŠ©/æ‰“è³
reward:
  # æ˜¯å¦å•Ÿç”¨æ‰“è³
  enable: true
  # æ‰“è³æ¡ˆä¾‹æ–‡æœ¬
  text: èµèµä½œè€…ï½
  QR_code:
    - img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/wxpay.webp
    #   link:
      text: å¾®ä¿¡
    - img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/alipay.webp
    #   link:
      text: æ”¯ä»˜å®

toc:
  post: true
  page: false
  number: true
  expand: false
  # Only for post
  style_simple: false
  scroll_percent: true

post_meta:
  # Home Page
  page:
    # Choose: created / updated / both
    date_type: created
    # Choose: date / relative
    date_format: date
    categories: true
    tags: false
    label: false
  post:
    # Choose: left / center
    position: left
    # Choose: created / updated / both
    date_type: both
    # Choose: date / relative
    date_format: relative
    categories: true
    tags: true
    label: true


# ä¾§è¾¹æ 
aside:
  enable: true
  hide: false
  button: true
  mobile: false     # display on mobile
  position: right   # left or rightï¼Œå†³å®šä¾§è¾¹æ åœ¨å³è¾¹è¿˜æ˜¯åœ¨å·¦è¾¹
  card_author:
    enable: true
    description: ä¸€ä¸ªäºº
    button:
      enable: true
      icon: fab fa-github
      text: æçš„ä¸€çš„Githubä¸»é¡µ
      link: https://github.com/zip95297
  card_announcement: 
    enable: true
    content: æœ€è¿‘æ²¡ä»€ä¹ˆè¦åˆ†äº«çš„
  card_recent_post:
    # æ˜¯å¦é¡¯ç¤ºæœ€è¿‘æ–‡ç« å¡ç‰‡
    enable: true
    # é¡¯ç¤ºæ–‡ç« æ•¸é‡ï¼Œ0 è¡¨ç¤ºé¡¯ç¤ºæ‰€æœ‰
    limit: 2
  card_archives:
    # æ˜¯å¦é¡¯ç¤ºæ­¸æª”å¡ç‰‡
    enable: false

share:
  # é¸æ“‡ï¼šsharejs / addtoany
  # å¦‚æœä¸éœ€è¦åˆ†äº«åŠŸèƒ½ï¼Œä¿æŒç‚ºç©º
  use: sharejs

  # Share.js
  # https://github.com/overtrue/share.js
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq

  # AddToAny
  # https://www.addtoany.com/
  addtoany:
    item: facebook,twitter,wechat,sina_weibo,facebook_messenger,email,copy_link

# é¼ æ¨™é»æ“Šæ•ˆæœ: æ–‡å­—
clickShowText:
  # æ˜¯å¦å•Ÿç”¨æ–‡å­—æ•ˆæœ
  enable: true
  text:
     - zzZ
     - Zzz
     - zZz
  fontSize: 15px
  # æ˜¯å¦éš¨æ©Ÿé¡¯ç¤ºæ–‡å­—
  random: false
  # æ˜¯å¦åœ¨ç§»å‹•è¨­å‚™ä¸Šå•Ÿç”¨
  mobile: true


# é è…³è¨­ç½®
footer:
  owner:
    # æ˜¯å¦å•Ÿç”¨æ‰€æœ‰è€…é¡¯ç¤º
    enable: true
    # ç¶²ç«™å‰µå»ºå¹´ä»½
    since: 2002
  # è‡ªå®šç¾©æ–‡æœ¬
  custom_text: åªæœ‰è¿™ä¹ˆç‚¹ä¸œè¥¿
  # ä¸»é¡Œå’Œæ¡†æ¶çš„ç‰ˆæ¬Šè²æ˜
  copyright: false

social:
  fab fa-github: https://github.com/zip95297 || Github || "#hdhfbb"
  fas fa-envelope: mailto:zip95297@gmail.com || Email || "#000000"







menu:
  ä¸»é¡µ: / || fas fa-home
  åšæ–‡ || fa fa-graduation-cap:
    åˆ†ç±»: /categories/ || fa fa-archive
    æ ‡ç­¾: /tags/ || fa fa-tags
    å½’æ¡£: /archives/ || fa fa-folder-open
  ç”Ÿæ´» || fas fa-list:
    åˆ†äº«: /share/ || fa fa-comments-o
    ç›¸å†Œ: /photos/ || fa fa-camera-retro
    éŸ³ä¹: /music/ || fa fa-music
    å½±è§†: /movies/ || fas fa-video
  å‹é“¾: /links/ || fa fa-link
  ç•™è¨€æ¿: /comment/ || fa fa-paper-plane
  å…³äºç¬”è€…: /about/ || fas fa-heart  


# Code Blocks (ä»£ç å—æ ·å¼)
# --------------------------------------
highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button æ˜¯å¦æ˜¾ç¤ºå¤åˆ¶æŒ‰é’®
highlight_lang: true # show the code language å±•ç¤ºä»£ç å—è¯­è¨€
highlight_shrink: false # true: æ‰“å¼€æ–‡ç« é»˜è®¤æŠ˜å ä»£ç å—å†…å®¹ / false: æ‰“å¼€æ–‡ç« é»˜è®¤å±•å¼€ä»£ç å—å†…å®¹
highlight_height_limit: false # unit: px
code_word_wrap: false #æ˜¯å¦å…³é—­æ»šåŠ¨æ¡

# Local search
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "åäº†åäº†ï¼æ²¡æ‰¾åˆ° ${query}" # å¦‚æœæ²¡æœ‰æŸ¥åˆ°å†…å®¹ç›¸å…³å†…å®¹æ˜¾ç¤º

# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (å¼€å¯æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: true
  # sourceèª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨æå¤©apiçš„éš¨æ©ŸèªéŒ„ï¼ˆç°¡é«”ï¼‰
  # source: 2  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰
  # source: 3  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰
  # source: 4  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœæœ‰è‹±æ–‡é€—å·' , ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &#44;
  # å¦‚æœæœ‰è‹±æ–‡åŒå¼•å·' " ',è¯·ä½¿ç”¨è½¬ä¹‰å­—å…ƒ &quot;
  # å¼€å¤´ä¸å…è¨±è½¬ä¹‰å­—å…ƒï¼Œå¦‚éœ€è¦ï¼Œè¯·æŠŠæ•´å€‹å¥å­ç”¨åŒå¼•å·åŒ…ä½
  # å¦‚æœå…³é—­æ‰“å­—æ•ˆæœï¼Œsubtitleåªä¼šç°ç¤ºsubçš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - å¹¿å‘Šä½ğŸª§æ‹›ç§Ÿ
    - æ‹›ç§ŸğŸª§å¹¿å‘Šä½
#    - å¹¿å‘Šä½ğŸª§æ‹›ç§Ÿ

# å¤´åƒ
avatar:
  img: https://cdn.jsdelivr.net/gh/zip95297/zip95297.github.io@main/source/images/profile/profile.webp?raw=true
  effect: false  # æ˜¯å¦å¯ç”¨å¤´åƒæ—‹è½¬æ•ˆæœï¼ˆå¯é€‰ï¼‰



# ä¸‹é¢è®¾ç½®ä¸€ä¸‹ å¯¹æ•°å­¦å…¬å¼çš„æ¸²æŸ“
math:
  enable: true
  per_page: true     # â† å¼€å¯æ¯ç¯‡æ–‡ç« å•ç‹¬æ§åˆ¶
  engine: mathjax    # æˆ–è€… katex
  mathjax:
    src: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  katex:
    css: https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css
    js: https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.js


